[package]
name = "ddtank-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sciter-rs = "0.5.58"
ureq = { version = "*", features = ["cookies", "charset"] }
select = "0.5.0"
url = "2.2"
anyhow = "1.0"
