[package]
name = "ddtank-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sciter-rs = "0.5.58"
anyhow = "1.0"
glob = "0.3.1"
rlua = "0.19.4"
reqwest = { version = "0.11.14", features = ["blocking", "cookies"] }

[build-dependencies]
embed-manifest = "1.3.1"
which = "4.4.0"
